### ISSUE TITLE
Error when running Sartools Deseq2 through galaxy

### ISSUE THREAD

**Issue by inestiouiri** [PF2-pasteur-fr/SARTools-Galaxy#2]
Hi all ,
I'm running sartools deseq2 on my local galaxy instance and here is what i got. Help me please
![galaxy sartools](https://cloud.githubusercontent.com/assets/15051266/20666350/116abbda-b564-11e6-808b-d8d979a89e09.png)

**Comment by hvaret** [comment]
Dear @inestiouiri,
I am not a Galaxy specialist, could you please post the content of the *.log file generated by SARTools and containing the output of the R console?
Thanks,
Hugo

**Comment by inestiouiri** [comment]
Dear @hvaret,
Log file gives exactly the same thing please take a look.
![deseq2 r log](https://cloud.githubusercontent.com/assets/15051266/20708219/551bbae8-b62f-11e6-91c3-c22c8d80bd59.png)

**Comment by hvaret** [comment]
OK thanks, unfortunately I can't figure out what happened. @loraine-gueguen, do you know where the error could come from?
Thanks!
Hugo

**Comment by inestiouiri** [comment]
and when i execute the Rscript command from the terminal 

![rscript](https://cloud.githubusercontent.com/assets/15051266/20708654/4a790102-b631-11e6-838c-d38f0b4378f8.png)

i got that 


[logsartools.txt](https://github.com/PF2-pasteur-fr/SARTools-Galaxy/files/618876/logsartools.txt)
[logsartools.txt](https://github.com/PF2-pasteur-fr/SARTools-Galaxy/files/618895/logsartools.txt)

**Comment by hvaret** [comment]
OK it is strange because SARTools seems to be correctly loaded but then the execution is stopped.

**Comment by loraine-gueguen** [comment]
Can you please have a look at the R log dataset generated as output as said Hugo, not on the errors, but on the content of the file ("view data" with the small eye on the Galaxy dataset) ?

**Comment by inestiouiri** [comment]
Dear @loraine-gueguen,

It gives that 

[1] "rawDir must be a character vector of length 1 specifying an accessible directory"

**Comment by loraine-gueguen** [comment]
ok. Can you please give me the format (or datatype) displayed in Galaxy of your dataset given as sartools input for 'Zip file containing raw counts files' (should be no_unzip.zip) ?

**Comment by inestiouiri** [comment]
Dear @loraine-gueguen,

I used test data of sartools  and yes it's a no_zip.zip file and for target file i used the target.txt.

![nounzip](https://cloud.githubusercontent.com/assets/15051266/20759789/463dd426-b71e-11e6-8136-62c141727a79.png)

**Comment by loraine-gueguen** [comment]
Make sure you have read rights on the directory given as argument for rawDir (and on all the files inside) and then please try to run the Rscript command again from a terminal after removing the stdout redirection  `> /usr/.../*.dat `
What appears on stdout ?

**Comment by inestiouiri** [comment]
Deat @loraine-gueguen,

i still have the same problem. :( and the Rscript command still load all packages and give out. 
 "Welcome to SARTools version 1.3.2.
 R template scripts are available on GitHub."
When we read the log we find that the tool is looking for files under /usr/local/galaxy/database/job_working_directory/001/1275 and when we go to see what we have we find under 001 a different directory which is 
/usr/local/galaxy/database/job_working_directory/001/1265.  :(

**Comment by loraine-gueguen** [comment]
Don't use the Galaxy tree: copy the input files (target and rawdir) in a new working directory, run the Rscript and see what happens.

**Comment by inestiouiri** [comment]
Welcome to SARTools version 1.3.2.
    R template scripts are available on GitHub.
    ----------------------------------------------
[1] "All the parameters are correct"
Target file:
    label         files group
WT1   WT1 WT1.htseq.out    WT
WT2   WT2 WT2.htseq.out    WT
KO1   KO1 KO1.htseq.out    KO
KO2   KO2 KO2.htseq.out    KO
Loading files:
WT1.htseq.out: 8222 rows and 183 null count(s)
WT2.htseq.out: 8222 rows and 193 null count(s)
KO1.htseq.out: 8222 rows and 210 null count(s)
KO2.htseq.out: 8222 rows and 193 null count(s)

Features removed:
alignment_not_unique
ambiguous
no_feature
not_aligned
too_low_aQual

Top of the counts matrix:
           WT1  WT2 KO1  KO2
feat0001  2728 1636 668 2378
feat0002  3169 1892 376 1228
feat0003  2784 1626 622 2117
feat0004  6311 4283 374 1470
feat0005 12769 9132 718 3199
feat0006  3953 2867 666 2579

Bottom of the counts matrix:
         WT1 WT2 KO1 KO2
feat8212   0   0   0   0
feat8213   1   0   0   1
feat8214   0   2   0   1
feat8215  15  14   5   5
feat8216  45  49  13  27
feat8217   1   0   0   0
Error in title(...) :
  X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 5 at size 12 could not be loaded
Calls: descriptionPlots ... plot.density -> plot.default -> localTitle -> title
Execution halted    
:o

**Comment by hvaret** [comment]
I think the problem now comes from the machine you're hosting Galaxy. I think a Linux library/package is missing.

**Comment by loraine-gueguen** [comment]
I think so too.

**Comment by inestiouiri** [comment]
Dear @loraine-gueguen and @hvaret,

Ok.Thank you so much guys for you quick answers.  :)
